import Delorean from "../images/cars-big/delorean.png";
import Batmobile1 from "../images/cars-big/batmobile1.png";
import kitt1 from "../images/cars-big/kitt1.png";
import Ectomobile from "../images/cars-big/Ectomobile.png";
import mistery1 from "../images/cars-big/mistery1.webp";
import Warthog from "../images/cars-big/Warthog.webp";
import mach5 from "../images/cars-big/mach5.webp";
import supra1 from "../images/cars-big/supra1.jpg";
import impala from "../images/cars-big/impala1.png";
import herbie from "../images/cars-big/herbie1.png";
import ateam from "../images/cars-big/ateam1.png";
import bmw from "../images/cars-big/bmw1.webp";




export const CAR_DATA = [
  {
    name: "DeLorean DMC-12",
    price: "555",
    img: Delorean,
    model: "DMC-12",
    mark: "DeLorean",
    year: "1981",
    doors: "2",
    air: "Não",
    transmission: "Automatic",
    fuel: "Plutônio",
  },
  {
    name: "Batmobile",
    price: "999",
    img: Batmobile1,
    model: "Batmobile",
    mark: "Indústrias Wayne ",
    year: "2016",
    doors: "2",
    air: "Não",
    transmission: "Automatic",
    fuel: "Gasolina",
  },
  {
    name: "KITT",
    price: "321",
    img: kitt1,
    model: "Knight Industries Two Thousand",
    mark: "Knight Industries",
    year: "1982",
    doors: "2",
    air: "Sim",
    transmission: "Automatic",
    fuel: "Gasolina",
  },
  {
    name: "Ecto-1 (Ghostbusters)",
    price: "666",
    img: Ectomobile,
    model: "Ecto-1",
    mark: "Ghostbusters",
    year: "1959",
    doors: "4",
    air: "Não",
    transmission: "Manual",
    fuel: "Gasolina",
  },
  {
    name: "Máquina de mistério",
    price: "420",
    img: mistery1,
    model: "Mystery Machine",
    mark: "Mystery Inc.",
    year: "1969",
    doors: "2",
    air: "Não",
    transmission: "Manual",
    fuel: "Gasolina",
  },
  {
    name: "Warthog",
    price: "777",
    img: Warthog,
    model: "Warthog",
    mark: "UNSC",
    year: "2552",
    doors: "4",
    air: "Não",
    transmission: "Automatic",
    fuel: "Reator de fusão",
  },
  {
    name: "Mach 5",
    price: "1400",
    img: mach5,
    model: "Mach 5",
    mark: "Speed Racer",
    year: "2050",
    doors: "2",
    air: "Sim",
    transmission: "Manual",
    fuel: "Energia nuclear",
  },
  {
    name: "Supra",
    price: "400",
    img: supra1,
    model: "Supra",
    mark: "Toyota",
    year: "1995",
    doors: "2",
    air: "Não",
    transmission: "Manual",
    fuel: "Gasolina",
  },
  {
    name: "Chevrolet Impala",
    price: "666",
    img: impala,
    model: "Impala",
    mark: "Chevrolet",
    year: "1967",
    doors: "2",
    air: "Não",
    transmission: "Manual",
    fuel: "Gasolina",
  },
  {
    name: "Herbie",
    price: "100",
    img: herbie,
    model: "Volkswagen Beetle",
    mark: "Volkswagen",
    year: "1963",
    doors: "2",
    air: "Não",
    transmission: "Manual",
    fuel: "Gasolina",
  },
  {
    name: "The A-Team Van",
    price: "500",
    img: ateam,
    model: "GMC Vandura",
    mark: "GMC",
    year: "N/A",
    doors: "4",
    air: "Não",
    transmission: "Automatic",
    fuel: "Gasolina",
  },
  {
    name: "E46 BMW M3 GTR",
    price: "850",
    img: bmw,
    model: "M3 GTR",
    mark: "BMW",
    year: "2001",
    doors: "2",
    air: "Não",
    transmission: "Manual",
    fuel: "Gasolina",
  },
];
